### ISSUE TITLE
翻译如何与官方内容同步？

### ISSUE THREAD

**Issue by OlingCat** [rust-lang-cn/www.rust-lang.org#34]
我们的翻译是基于 `locales\en-US` 下的内容进行的。但当官方英文文档更新后，我们应当如何同步？

目前的想法是，在翻译文件的头部维护一个元信息，其中包括基于的原文件和提交 hash，然后写一个脚本或 git hook 帮助检查同步。

例如，我要开始翻译 `locales\zh-CN\learn.ftl`，那么可以先执行

```sh
git log -1 --format="%H" locales\en-US\learn.ftl
```

得到原文件最后一次提交的 hash `a245fdd5944dcfe0a04206fae15752856b7aaf2c`，然后在 `locales\zh-CN\learn.ftl` 头部添加如下内容：

```
# based-file: locales\en-US\learn.ftl
# commit-hash: a245fdd5944dcfe0a04206fae15752856b7aaf2c
```

之后开始翻译。

当原文件更新后，翻译文件元信息中记录的 hash 和原文件的提交 hash 会不一致，此时可以执行：

```
git diff a245fdd5944dcfe0a04206fae15752856b7aaf2c HEAD -- locales\en-US\learn.ftl
```

查看自上次翻译以来原文件的改动，然后译者手动更新翻译文件中的内容和 hash 再提交。

这些工作可以写一个 git 扩展或 git hook 来帮我们自动进行。
各位有何高见？

**Comment by ZhangHanDong** [comment]
目前官方不接受代码pr，用pontoon统一管理
