### ISSUE TITLE
为什么不直接使用Pontoon平台？

### ISSUE THREAD

**Issue by upsuper** [rust-lang-cn/www.rust-lang.org#52]
那个平台就是设计来协作翻译的，在里面可以很容易地看到每一条的原文和对应其他语言的翻译，以及历史修订和不同提议，也有专门的审核系统。参与翻译也只需要直接上到网站就可以进行，不需要fork项目本地修改再提交。官方内容更新也会即时地反映在上面。

单独开一个repo用来翻译不是纯粹自找麻烦同时又抬高参与门槛吗？

**Comment by ZhangHanDong** [comment]
@upsuper  

因为之前不了解pontoon平台 。。。233

于是就用GitHub协作了。还有就是想在本地跑起来，放到语境下，对翻译更有帮助。如果你在qq群的话，可能更能体会。

不过现在已经开始用Pontoon了，你如果愿意可以直接在pontoon上面校对。

**Comment by ZhangHanDong** [comment]
@upsuper 还有其他原因，我打算翻译完写篇文章记录下这个过程，到时候在里面也会解释。

**Comment by OlingCat** [comment]
Pontoon 平台有很多问题：
1. 不方便审校评注，互相之间的交流只能在 QQ 上，没办法留档。
2. 一些词语的整体替换不方便
3. 不能即时查看最终结果，因为有些语句跟语境和排版有关。

**Comment by Aimeedeer** [comment]
太赞了。求经验分享，也是给这个产品的反馈。估计其他国家同学也有这样的问题。

Oling Cat <notifications@github.com> 于2019年6月9日周日 下午11:17写道：

**Comment by ZhangHanDong** [comment]
对的，协作上有很多问题，需要先在pontoon之外处理好。 
我们通过github协作对官网的内容翻译和校对了一遍，然后再上pontoon，这样方便管理和保证质量。

@upsuper 我看你直接在pontoon上翻译，我觉得还是直接参与校对比较好，我们这边基本都翻译的差不多了。我需要在本地把官网跑起来，做整体的校对，目前还有些文件没有校对完。你可以直接从已经提交的ftl文件开始校对来参与。我和Florian交流过了，下周就把官网的文件都提交到pontoon上面。

**Comment by ZhangHanDong** [comment]
@upsuper 翻译的参与门槛，确实是需要提高的。至少应该是对Rust和社区有过了解的人参与比较好。

另外还有一些翻译术语，描述，容易扯皮的地方，最好是先通过GitHub来沟通好，就不用在Pontoon上面改来改去。至少GitHub有一个地方，可以公开的讨论这些东西。

**Comment by ZhangHanDong** [comment]
@upsuper tg上没法私聊你，就这里给你说了。

最后一个原因： 是为了让国内的Rust社区里的人都参与一下。报名翻译的人也比较多，用GitHub也是最好的。虽然我之前不了解Pontoon的功能，但是我现在觉得用GitHub协作的方式其实还不错。人多好管理。直接用Pontoon就太散了。

之前我推上发了招募翻译人员，你也没说你对翻译感兴趣，否则咱们提前一周就可以把事情交流得更好。现在我们翻译的差不多了，你突然又在Pontoon上面开始独立翻译了。我是觉得没必要，这样力量比较分散，你过来加入我们一起校对就好了。

**Comment by ZhangHanDong** [comment]
@upsuper  为了方便沟通，你也可以建个翻译小组的tg群，然后我让大家加入，方便交流，可以尽快在下周交付。

**Comment by upsuper** [comment]
> 不方便审校评注，互相之间的交流只能在 QQ 上，没办法留档。

这个确实不太方便，但GitHub上交流说实话我觉得也并不方便，异步交流的效率总是受到限制。沟通协调的时候还是面对面或者至少即时通讯会比较好。

基于留档的问题，我觉得QQ可能不是一个很好的平台（甚至Telegram也不是，特别对于中文来说）。IRC配合机器人存档有一些现成的工具可以方便查询，但IRC也逐渐日薄西山了。或许可以考察一下Discord和Slack是否合适。

> 一些词语的整体替换不方便

这确实也是一个问题，可以跟官方反馈，如果能够在上游Pontoon改进就更好了。Pontoon已经在Firefox等Mozilla项目上应用多年，不知道他们是如何解决这些问题的，或许可以联系相关人员了解一下……

> 不能即时查看最终结果，因为有些语句跟语境和排版有关。

这个问题可能是网站翻译比较独有的，或许也可以跟官方反馈一下。

不过个人觉得这个问题可能不是那么严重，因为如果网站是连续部署的，其实每次改动到上线时间不是很长，如果发现问题再改一般也没有特别大的影响。

> 我看你直接在pontoon上翻译，我觉得还是直接参与校对比较好，我们这边基本都翻译的差不多了。我需要在本地把官网跑起来，做整体的校对，目前还有些文件没有校对完。你可以直接从已经提交的ftl文件开始校对来参与。我和Florian交流过了，下周就把官网的文件都提交到pontoon上面。

我对Pontoon平台本身不是特别了解，但上面似乎可以留团队信息。可以考虑像[葡萄牙语团队](https://pontoon.rust-lang.org/pt-BR/info/)那样至少在团队信息里留一个联系方式，这样方便别人找到组织。

翻译项目，沟通交流是很重要的，感觉Pontoon更主要是作为翻译平台，协调和沟通交流的方式由团队自己决定。但也许有些方面更集成会更好。

**Comment by ZhangHanDong** [comment]
@upsuper  其实最主要的原因就是最初组织翻译小组的时候没有了解过Pontoon的功能，而且官网仓库最初是有一个i18n分支，以为可以通过github pr来提交。 后来发现官网把分支取消了，和Florian沟通的时候才了解到Pontoon的作用，其实也就是上周。 

之前我想建个tg群来着，但是最近国内的形势，大家可能不太好用tg，就没有建。

**Comment by ZhangHanDong** [comment]
@upsuper  https://pontoon.rust-lang.org/zh-CN/rust-www/team-info/  团队信息刚加上，之前我们没有权限修改。

**Comment by Aimeedeer** [comment]
我的错，在开始阶段的时候没有进一步做工具上的沟通，大家都很快上手翻译了。
Pontoon 也有很多不足的地方，bug 也有，大家之后有发现问题也一起反馈一下，官方也需要大家的反馈才好优化。

**Comment by ZhangHanDong** [comment]
@Aimeedeer  

提个意见：Pontoon应该把flt文件的导入和导出功能都支持上，现在只能导出，不能导入。

**Comment by upsuper** [comment]
> 我的错，在开始阶段的时候没有进一步做工具上的沟通，大家都很快上手翻译了。

我可能用词不太恰当，我本意也不是想指责谁，主要是觉得Pontoon应该是个不错的平台，建议考虑直接使用。但看起来沟通协调确实需要额外的通道。

或许初期翻译以后可以建个repo用于整理流程、用语、规范一类的内容，然后在Pontoon上放个链接指向这个repo，关于这些的讨论可以在这个repo上进行，而具体的翻译可以还放在Pontoon上，也方便更多人参与。具体讨论如果不求留档可以在QQ群或者TG群，但或许可以把结论适时更新在repo上。

关于全站预览的问题，Pontoon的文档里有提到它[提供了实时预览的编辑器](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/ui.html#pontoon-in-context-editor)，可能目前Rust项目还没配置好？这个或许可以跟官方提议一下。
