### ISSUE TITLE
tools

### ISSUE THREAD

**Issue by huangjj27** [rust-lang-cn/www.rust-lang.org#8]
翻译 tools.flt

- [x] 翻译
- [x] 校对

**Comment by 0kaguya** [comment]
唔，我是打算翻译tools/install这部分的，不知道会不会冲突
如果不方便的话我就负责校对？

**Comment by huangjj27** [comment]
> 唔，我是打算翻译tools/install这部分的，不知道会不会冲突

感谢!

**Comment by aaranxu** [comment]
完成内容校对，请确认

**Comment by OlingCat** [comment]
Closed by #20

**Comment by OlingCat** [comment]
翻译完毕，见 https://pontoon.rust-lang.org/zh-CN/rust-www/tools.ftl/
